import type { LayerSpecification } from "maplibre-gl";

export const defaultLayers: Array<LayerSpecification> = [
  {
    filter: ["any", ["has", "building"], ["has", "building:part"]],
    id: "buildings-background",
    paint: {
      "fill-color": "#FFFFFF",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 16.5, 0, 18, 1],
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "indoor"], "level"],
    id: "level-background",
    paint: {
      "fill-color": "#FBF9FA",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 16.5, 0, 18, 1],
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "leisure"], "garden"],
    id: "indoor-gardens",
    layout: {
      visibility: "visible",
    },
    paint: {
      "fill-color": "#D8E5A4",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "amenity"], "parking"],
    id: "indoor-parkings",
    paint: {
      "fill-color": "#fbeada",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
      "fill-outline-color": "#000000",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "amenity"], "parking"],
    id: "indoor-parkings-patterns",
    paint: {
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 0.1],
      "fill-pattern": "si-main-3",
      "fill-translate-anchor": "viewport",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "indoor"],"corridor"],
    id: "indoor-corridors",
    paint: {
      "fill-antialias": true, // otherwise the outline is invisible sometimes..,
      "fill-color": "#8dd1fc",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
      "fill-outline-color": "#000",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: [
      "any",
      ["==", ["get", "indoor"], "room"],
      ["==", ["get", "indoor"], "area"],
      ["==", ["get", "railway"], "platform"],
    ],
    id: "indoor-rooms",
    paint: {
      "fill-antialias": true, // otherwise the outline is invisible sometimes..
      "fill-color": "#e0e0e0",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
      "fill-outline-color": "#000",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "indoor"] ,"room"],
    id: "indoor-rooms-borders",
    paint: {
      "line-color": "#000",
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
      "line-width": 1,
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: ["==", ["get", "indoor"], "area"],
    id: "indoor-areas",
    paint: {
      "fill-color": "#b9e1ff",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["all",
      ["==", ["get", "highway"], "pedestrian"],
      ["has", "level"]
    ],
    id: "indoor-highways-area",
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        16,
        "hsl(230, 16%, 94%)",
        16.25,
        "hsl(230, 50%, 98%)",
      ],
      "fill-opacity": 1,
      "fill-outline-color": "hsl(230, 26%, 88%)",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["all", ["==", ["get", "highway"], "pedestrian"], ["has", "level"]],
    id: "indoor-highways-area-pattern",
    paint: {
      "fill-color": "hsl(0, 0%, 100%)",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
      "fill-outline-color": "hsl(35, 10%, 83%)",
      "fill-pattern": "pedestrian-polygon",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["all",
      ["==", ["get", "indoor"], "area"],
      ["==", ["get", "balcony"], "yes"]
    ],
    id: "indoor-balcony",
    paint: {
      "fill-color": "#BDBDBD",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: [
      "any",
      ["==", ["get", "stairs"], "yes"],
      ["==", ["get", "elevator"], "yes"],
      ["==", ["get", "highway"], "elevator"],
    ],
    id: "indoor-stairs",
    paint: {
      "fill-color": "#5a7c94",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
      "fill-outline-color": "#000000",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "indoor"], "wall"],
    id: "indoor-walls",
    paint: {
      "line-color": "#000000",
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: ["has", "barrier"],
    id: "indoor-barriers",
    paint: {
      "line-color": "#000000",
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: ["==", ["get", "indoor"], "block"],
    id: "indoor-blocks",
    paint: {
      "fill-color": "#000000",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 18, 1],
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["==", ["get", "handrail"], "yes"],
    id: "indoor-handrail",
    paint: {
      "line-color": "#000000",
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 19, 1],
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: ["==", ["get", "railway"], "rail"],
    id: "indoor-rails",
    paint: {
      "line-color": "hsl(230, 10%, 74%)",
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 19, 1],
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: ["==", ["get", "railway"], "rail"],
    id: "indoor-rails-tracks",
    paint: {
      "line-color": "hsl(230,10%,74%)",
      "line-dasharray": [0.1, 15],
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 19, 1],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        14,
        4,
        20,
        8,
      ],
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: [
      "any",
      ["in", ["get", "indoor"], ["literal",["table", "cupboard","chair","kitchen","sofa","tv","shelf","furniture-item",]]],
      ["==", ["get", "trashcan"], "yes"],
      ["==", ["get", "copier"], "yes"],
      ["==", ["get", "amenity"], "vending_machine"],
    ],
    id: "indoor-furniture",
    paint: {
      "fill-color": "#000",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 18, 0, 19, 0.2],
      "fill-outline-color": "#000",
    },
    source: "indoor",
    type: "fill",
  },
  {
    filter: ["all", ["==", ["get", "highway"], "steps"], ["!", ["has", "conveying"]]],
    id: "indoor-steps",
    layout: {
      "line-join": "round",
    },
    paint: {
      "line-color": "hsl(0,0%,100%)",
      "line-dasharray": [
        "step",
        ["zoom"],
        ["literal", [1, 0]],
        17.5,
        ["literal", [1.75, 1]],
        18,
        ["literal", [1, 0.75]],
        19,
        ["literal", [0.3, 0.3]],
      ],
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 17.25, 1],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        17,
        1,
        18,
        1.6,
        19,
        6,
      ],
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: ["all", ["==", ["get", "highway"], "steps"], ["has", "conveying"]],
    id: "indoor-conveying",
    layout: {
      "line-join": "round",
    },
    paint: {
      "line-color": "#FF0000",
      "line-dasharray": [
        "step",
        ["zoom"],
        ["literal", [1, 0]],
        17.5,
        ["literal", [1.75, 1]],
        18,
        ["literal", [1, 0.75]],
        19,
        ["literal", [0.3, 0.3]],
      ],
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 17, 0, 17.25, 1],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        17,
        1,
        18,
        1.6,
        19,
        6,
      ],
    },
    source: "indoor",
    type: "line",
  },
  {
    filter: ["==", ["get", "indoor"], "room"],
    id: "poi-indoor-text-ref",
    layout: {
      "symbol-placement": "point",
      "text-allow-overlap": false,
      "text-anchor": "center",
      "text-field": [
        "format",
        ["get", "name"],
        {"font-scale": 0.8},
        "\n",
        {},
        ["get", "ref"],
        {"font-scale": 0.6}
      ],
      "text-font": ["Roboto Regular"],
      "text-ignore-placement": false,
      "text-letter-spacing": 0.02,
      "text-line-height": 1.2,
      "text-max-angle": 38,
      "text-max-width": 8,
      "text-padding": 2,
      "text-rotation-alignment": "viewport",
      "text-size": ["interpolate", ["linear"], ["zoom"], 17, 10, 20, 12],
      visibility: "visible",
    },
    minzoom: 17,
    paint: {
      "text-color": "#072140",
      "text-halo-color": "rgb(194, 215, 239, 0.3)",
      "text-halo-width": 1,
      "text-opacity": [
        "interpolate",
        ["linear"],
        ["zoom"],
        18,
        0,
        18.5,
        0.5,
        19,
        1,
      ],
    },
    source: "indoor",
    type: "symbol",
  },
  {
    filter: ["boolean", false], // changed in the poi-logic
    id: "poi-indoor",
    layout: {
      "icon-allow-overlap": true,
      "icon-anchor": "center",
      "icon-image": ["get", "maki"], // changed in the poi-logic
      "icon-optional": false,
      "icon-size": ["interpolate", ["linear"], ["zoom"], 17, 0.5, 20, 1],
      "symbol-placement": "point",
      "symbol-spacing": 250,
      "text-allow-overlap": false,
      "text-anchor": "top",
      "text-field": [
        "format",
        ["get", "name"],
        {"font-scale": 0.8},
        "\n",
        {},
        ["get", "ref"],
        {"font-scale": 0.6}
      ],
      "text-font": ["Roboto Regular"],
      "text-ignore-placement": false,
      "text-letter-spacing": 0.02,
      "text-line-height": 1.2,
      "text-max-angle": 38,
      "text-max-width": 8,
      "text-offset": [0, 1],
      "text-padding": 2,
      "text-rotation-alignment": "viewport",
      "text-size": ["interpolate", ["linear"], ["zoom"], 17, 11, 20, 13],
      visibility: "visible",
    },
    minzoom: 17,
    paint: {
      "icon-opacity": [
        "interpolate",
        ["linear"],
        ["zoom"],
        17,
        0,
        17.5,
        0.5,
        19,
        1,
      ],
      "text-color": "#072140",
      "text-halo-color": "rgb(194, 215, 239, 0.3)",
      "text-halo-width": 1,
      "text-opacity": [
        "interpolate",
        ["linear"],
        ["zoom"],
        17,
        0,
        17.5,
        0.5,
        19,
        1,
      ],
    },
    source: "indoor",
    type: "symbol",
  },
];
