name: build

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [10.23.0, 12.19.0, 14.15.0]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint
