name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [20, 22]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0
          package_json_file: package.json
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm test
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [20, 22]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0
          package_json_file: package.json
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm run build
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0
          package_json_file: package.json
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: npm run lint
